### PR TITLE
Milestone 6: Friendships v2

### PR DESCRIPTION
**Pull request by 410AngelaVu**
In this milestone, I have created:
- Enhance feature tests with before: example method.
- That Current users can only see their posts and those of their friends.

### CODE REVIEW

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Invalid Submission :red_circle: 
##### I will be marking this PR as invalid. If you need help you can reach out to me on slack or to any of the full-time TSE. Please, for next time, when you have a project and you need help understanding it, first approach any of the full-time TSE for help as opposed to submitting an incomplete.
slack(@ebeagusamuel)

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Changes Required! ♻️
### Hi @410AngelaVu 👏 👏
#### Well done 💪 you have done a good job on this project and written such a comprehensive test is a good one. However, some requirements are missing/not implemented correctly. Check my comments below 👇

#### 1) LINTER:
 - Enable linter for this Pull Request.
 - Check the project with `rubocop .` command: there are some errors.

#### 2) PULL REQUEST:
 - Improve the Pull Request description, add more details about what you have done in the project.
 
#### 3) APP BEHAVIOUR:
 - Current users should only see their posts and those of their friends. As mentioned here "PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))"

#### _Reviewed by Temitayo Adeleke_

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've done an excellent job so far. 
The main features seem to be working, you're almost there :clap: 
However, some changes are required before this milestone can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] As mentioned by the previous reviewer, your linter checks (GitHub Actions) are not running. Please make sure that all checks run successfully before you submit another review request.
- [x] Your PR title is not descriptive. Using a commit message as you did is not a good practice. Please change the PR title to a descriptive and meaningful one.

- [x] In subsequent commits, always commit often. This is important for you to keep track of how you implemented the changes.


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Request changes :full_moon:
**Hi AngelaVu**
**Great job so far in making some of the changes requested by the previous Tse :clap: :clap:. However, we still need to make a few changes in order to get this project approved :muscle:**

- [x] The .rubocop.yml config seems to have been altered in this project. see screen-shot for reference:
image
Take some time to study the linter-config/ror readme using this link: https://github.com/microverseinc/linters-config/tree/master/ror

Make the required changes and submit another code review request when you are done.

You can reach me on slack @ Eric Enaburekhan if you have any questions.
Happy coding:blush:
Eric Enaburekhan

**Review by voscarmv — APPROVED** [review]
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
